# Generated by Django 5.1.8 on 2025-05-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='nlast_name',
            new_name='last_name',
        ),
    ]
