# Generated by Django 5.1.8 on 2025-05-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('staff', 'Staff')], default='doctor', max_length=10),
        ),
    ]
